name: flutter_video_share_page
description: Landing page for shared videos from the app, available at share.vibesonly.com

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.4.0
  http: ^1.2.2
  url_launcher: ^6.1.6
  just_audio: ^0.10.4
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf

  assets:
    - assets/logo.png
    - assets/app_store_button.png
    - assets/play_store_button.png