name: sealed_annotations
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/6thsolution/dart_sealed/tree/master/sealed_annotations
homepage: https://github.com/6thsolution/dart_sealed

version: 1.13.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.17.0
  equatable: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3

# remove this on pub branch
publish_to: 'none'
