name: sealed_generators
description: Dart and Flutter sealed or union class generator and annotations, with match methods and other utilities.
repository: https://github.com/6thsolution/dart_sealed/tree/master/sealed_generators
homepage: https://github.com/6thsolution/dart_sealed

version: 1.13.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # use fixed version dependency
  sealed_annotations: '1.13.0'
  # use fixed version dependency
  sealed_writer: '1.13.0'
  build: ^4.0.0
  source_gen: ^4.0.1
  analyzer: ^8.2.0
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  build_test: ^3.4.0

# remove this on pub branch
publish_to: 'none'

# remove this on pub branch
dependency_overrides:
  sealed_annotations:
    path: ../sealed_annotations
  sealed_writer:
    path: ../sealed_writer
