name: vibes_only
description: Vibes Only flutter application

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+33

# Android build version
# version: 1.0.3+6

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  adaptive_theme: ^3.0.0
  shared_preferences: ^2.0.6
  flutter_bloc: ^8.1.1
  get_it: ^8.2.0
  intl: ^0.20.2
  sealed_annotations: ^1.8.0
  video_player: ^2.2.7
  inview_notifier_list:
    git:
      url: https://github.com/SteepSheep/inview_notifier_list.git
  rive: ^0.13.13
  retrofit: ^4.9.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.0
  audio_service: ^0.18.0-beta.0
  just_audio: ^0.10.4
  audio_video_progress_bar: ^2.0.3
  rxdart: ^0.28.0
  vibes_common:
    path: ../flutter_common
  flutter_mobile_app_presentation:
    path: ../flutter_mobile_app_presentation
  encrypt: ^5.0.1
  flutter_blue_plus: ^2.0.0
  crypto: ^3.0.1
  sliding_switch: ^1.0.0
  share_plus: ^12.0.0
  subtitle_wrapper_package: ^2.0.1
  url_launcher: ^6.0.17
  firebase_core: ^4.0.0
  google_sign_in: ^6.2.1
  firebase_auth: ^6.0.1
  sign_in_with_apple: ^7.0.1
  transparent_image: ^2.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  smooth_page_indicator: ^1.0.0+2
  flare_flutter:
    path: ../packages/flare_flutter
  flutter_svg: ^2.0.2
  firebase_analytics: ^12.0.0
  package_info_plus: ^9.0.0
  firebase_database: ^12.0.0
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5
  dotted_border: ^3.1.0
  go_router: ^16.1.0
  dio: ^5.0.1
  equatable: ^2.0.5
  purchases_flutter: ^9.2.1
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  collection: ^1.17.0
  google_fonts: ^6.2.1
  sensors_plus: ^7.0.0
  #  spotify_sdk: ^3.0.0-dev.2
  http: ^1.2.2
  gap: ^3.0.1
  custom_sliding_segmented_control: ^1.8.1
  miniplayer: ^1.0.1
  record: ^6.0.0
  wave: ^0.2.2
  flutter_blue_plus_platform_interface: ^8.0.0
  animate_do: ^4.2.0
  hugeicons: ^1.0.2
  pin_code_fields: ^8.0.1
  flutter_card_swiper:
    path: ../packages/flutter_card_swiper
  flutter_markdown_plus: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  flutter_gen_runner: ^5.2.0
  sealed_generators:
    path: ../packages/dart_sealed-patch-1/sealed_generators
  intl_utils: ^2.4.0
  retrofit_generator: ^10.2.0
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.0.7

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/like.riv
    - assets/dev_connected.flr
    - assets/toy.flr
    - assets/vibe_patterns/

flutter_intl:
  enabled: true
