name: flutter_panel
description: Admin Panel

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sealed_annotations: ^1.8.0
  shimmer: ^3.0.0
  json_annotation: ^4.1.0
  auto_route: ^9.2.2
  vibes_common:
    path: ../flutter_common
  flutter_mobile_app_presentation:
    path: ../flutter_mobile_app_presentation
  iconly: ^1.0.1
  retrofit: ^4.0.1
  get_it: ^8.2.0
  flutter_bloc: ^8.1.6
  adaptive_theme: ^3.0.0
  device_preview: ^1.0.0
  transparent_image: ^2.0.0
  password_credential: ^0.3.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  universal_io: ^2.0.4
  multiselect_formfield: ^0.1.6
  multi_select_flutter: ^4.0.0
  file_picker: ^8.1.2
  pretty_dio_logger: ^1.1.1
  http: ^1.2.2
  url_launcher: ^6.0.17
  string_validator: ^1.0.0
  harmony_auth: ^3.4.0
  harmony_log: ^2.0.2
  universal_html: ^2.0.9
  dio: ^5.0.1
  meta: ^1.8.0
  timezone: ^0.9.2
  flutter_blue_plus: ^2.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sealed_generators:
    git:
      url: https://github.com/GreyElaina/dart_sealed.git
      path: sealed_generators
      ref: patch-1
  intl_utils: ^2.4.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.1.2
  flutter_gen_runner: ^5.2.0
  retrofit_generator: ^9.0.0
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.otf
        - asset: fonts/Poppins-Light.otf
        - asset: fonts/Poppins-Regular.otf
    - family: vibes
      fonts:
        - asset: assets/fonts/vibes.ttf

  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_intl:
  enabled: true

flutter_gen:
  output: lib/generated/
