name: flutter_mobile_app_presentation
description: >
  Constitutes the presentation layer of the Vibes Only mobile app. 
  It can be used by the actual mobile app, or the mobile simulator of the admin panel, 
  with possibly different data (e.g. mock data in some parts of the simulator).
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  vibes_common:
    path: ../flutter_common
  audio_service: ^0.18.12
  flutter_bloc: ^8.1.3
  get_it: ^8.2.0
  just_audio: ^0.10.4
  sealed_annotations: ^1.13.0
  firebase_crashlytics: ^5.0.0
  equatable: ^2.0.5
  firebase_auth: ^6.0.1
  package_info_plus: ^9.0.0
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  retrofit: ^4.9.1
  collection: ^1.17.0
  mobx: ^2.2.1
  url_launcher: ^6.1.11
  rive: ^0.13.13
  subtitle_wrapper_package: ^2.2.1
  inview_notifier_list:
    git:
      url: https://github.com/SteepSheep/inview_notifier_list.git
  share_plus: ^12.0.0
  video_player: ^2.7.2
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  firebase_messaging: ^16.0.0
  rxdart: ^0.28.0
  flutter_mobx: ^2.2.0
  flare_flutter:
    path: ../packages/flare_flutter
  flutter_svg: ^2.0.5
  firebase_analytics: ^12.0.0
  adaptive_theme: ^3.2.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  flutter_blue_plus: ^2.0.0
  webview_flutter: ^4.8.0
  intl: ^0.20.2
  hugeicons: ^1.0.2
  flutter_widget_from_html_core: ^0.17.0
  flutter_markdown_plus: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  flutter_gen_runner: ^5.2.0
  sealed_generators:
    path: ../packages/dart_sealed-patch-1/sealed_generators
  intl_utils: ^2.4.0
  retrofit_generator: ^10.2.0
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.0.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family: vibes
      fonts:
        - asset: assets/fonts/vibes.ttf
    - family: vibes_v2
      fonts:
        - asset: assets/fonts/vibes_v2.ttf
    - family: vibes_v3
      fonts:
        - asset: assets/fonts/vibes_v3.ttf
  assets:
    - assets/
    - assets/images/
    - assets/svgs/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
